apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk2-pv
  labels:
    usage: monitoring
  namespace: monitoring 
spec:
  storageClassName: zabbix-postgres
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mr/zabbix
