kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mysql-wordpress
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-wp-pv-volume
  labels:
    type: local
  namespace: wordpress
spec:
  storageClassName: mysql-wordpress
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/wp4801"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-wp-pv-claim
  namespace: wordpress
spec:
  storageClassName: mysql-wordpress
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
